"use client";

import { motion } from "framer-motion";
import { Download, Clock, FileText } from "lucide-react";

interface PastResultBannerProps {
  title: string;
  subtitle?: string;
  onDownload?: () => void;
  children?: React.ReactNode;
}

export default function PastResultBanner({
  title,
  subtitle,
  onDownload,
  children,
}: PastResultBannerProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: -10 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-3xl border bg-gradient-to-br from-primary/5 to-primary/[0.02] p-6 shadow-sm backdrop-blur"
    >
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <div className="mt-0.5 rounded-xl bg-primary/10 p-2.5">
            <Clock className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-foreground">
              Past Result
            </h3>
            <p className="mt-0.5 text-sm text-muted-foreground">
              {title}
            </p>
            {subtitle && (
              <p className="mt-0.5 text-xs text-muted-foreground/70">
                {subtitle}
              </p>
            )}
          </div>
        </div>

        {onDownload && (
          <button
            onClick={onDownload}
            className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-primary/10 px-4 py-2 text-xs font-medium text-primary transition-all hover:bg-primary/20"
          >
            <Download className="h-3.5 w-3.5" />
            Download PDF
          </button>
        )}
      </div>

      {children && <div className="mt-4">{children}</div>}
    </motion.div>
  );
}

export function downloadAsPdf(filename: string, content: string) {
  const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${filename}</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.6; }
    h1 { color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
    h2 { color: #4f46e5; margin-top: 24px; }
    h3 { color: #3730a3; margin-top: 16px; }
    .score { display: inline-block; padding: 8px 24px; border-radius: 12px; font-size: 24px; font-weight: bold; }
    .score-high { background: #dcfce7; color: #166534; }
    .score-medium { background: #fef9c3; color: #854d0e; }
    .score-low { background: #fee2e2; color: #991b1b; }
    ul { margin: 8px 0; padding-left: 24px; }
    li { margin-bottom: 4px; }
    .section { margin: 16px 0; padding: 16px; background: #f8fafc; border-radius: 8px; border-left: 4px solid #6366f1; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; text-align: center; }
    .month-card { margin: 12px 0; padding: 16px; background: #f1f5f9; border-radius: 8px; }
    .month-card h3 { margin: 0 0 8px 0; }
    .topic { margin: 8px 0; padding: 8px 12px; background: white; border-radius: 6px; }
    pre { white-space: pre-wrap; background: #f1f5f9; padding: 16px; border-radius: 8px; font-size: 13px; }
  </style>
</head>
<body>
  ${content}
  <div class="footer">Generated by TalentSync AI</div>
</body>
</html>`;

  const blob = new Blob([htmlContent], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename.replace(/[^a-zA-Z0-9-_]/g, "_")}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}